# Use directly build/ content, don't rebuild website in docker build step
FROM stephaneklein/nginx-brotli:1.23.4
COPY build/ /usr/share/nginx/html/
COPY reports /usr/share/nginx/html/reports/
COPY nginx-config/default.conf /etc/nginx/conf.d/default.conf
