# This Docker image come from https://github.com/stephane-klein/nginx-brotli-docker/blob/main/Dockerfile
FROM stephaneklein/nginx-brotli:1.23.4
COPY reports /usr/share/nginx/html/reports/
COPY nginx-config/default.conf /etc/nginx/conf.d/default.conf
