version: '3.8'
services:
  nginx:
    image: stephaneklein/nginx-sklein.xyz:latest
    volumes:
    - ../nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - sklein_xyz

  sklein_xyz:
    image: stephaneklein/sklein.xyz:latest

  goatcounter:
    # Builder from https://github.com/tigattack/docker-goatcounter
    image: stephaneklein/goatcounter:latest
    ports:
    - 8080:8080
    environment:
      GOATCOUNTER_DOMAIN: "127.0.0.1"
      GOATCOUNTER_EMAIL: contact@stephane-klein.info
      GOATCOUNTER_PASSWORD: password
    volumes:
    - ./volumes/goatcounter/:/goatcounter/db/
