services:
  nginx:
    image: stephaneklein/nginx-sklein.xyz:latest
    restart: unless-stopped
    volumes:
    - ../nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      sklein_xyz:
        condition: service_healthy

  sklein_xyz:
    image: stephaneklein/sklein.xyz:latest
    restart: unless-stopped
    build: ../
    environment:
        POSTGRES_URL: postgres://postgres:password@postgres:5432/postgres
        GOTIFY_URL: "http://gotify"
        GOTIFY_KEY: "ASmAxUa-q1y7zqX"
        PUBLIC_GOATCOUNTER_URL: "http://127.0.0.1:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      start_period: 30s

  goatcounter:
    # Builder from https://github.com/tigattack/docker-goatcounter
    image: stephaneklein/goatcounter:latest
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      GOATCOUNTER_DOMAIN: "127.0.0.1"
      GOATCOUNTER_EMAIL: contact@stephane-klein.info
      GOATCOUNTER_PASSWORD: password
    volumes:
    - ./volumes/goatcounter/:/goatcounter/db/

  gotify:
    image: gotify/server:2.4.0
    restart: unless-stopped
    ports:
    - 9000:80
    environment:
      TZ: Europe/Paris
      GOTIFY_SERVER_PORT: 80
      GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: 0
      GOTIFY_SERVER_SSL_ENABLED: 'false'
      GOTIFY_DATABASE_DIALECT: sqlite3
      GOTIFY_DATABASE_CONNECTION: /data/gotify.db
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: admin
      GOTIFY_PASSSTRENGTH: 10
      GOTIFY_UPLOADEDIMAGESDIR: data/images
      GOTIFY_PLUGINSDIR: data/plugins
      GOTIFY_REGISTRATION: 'false'
    volumes:
      - ./volumes/gotify/:/data/

# Plausible

  plausible_db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - ./volumes/plausible/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./volumes/plausible/clickhouse/event-data/:/var/lib/clickhouse
      - ./volumes/plausible/clickhouse/event-logs/:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000:8000
    environment:
      DISABLE_REGISTRATION: true
      BASE_URL: http://localhost:8000
      SECRET_KEY_BASE: iXImFnvu8vmaJpMlwTrT+pVtd30MBmvz0I7WYW2KlZefGaiQVvv5ny9zUox0hgTb
      TOTP_VAULT_KEY: QFEKzBMIDMxFvRBZBIvdiGQilgnzRjvnEiPtsvtnjUI=
      ADMIN_USER_EMAIL: admin@example.com
      ADMIN_USER_NAME: admin
      ADMIN_USER_PWD: password
