name: Build and push to GitHub page
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - static/**
      - package.json
      - pnpm-lock.yaml
      - postcss.config.cjs
      - svelte.config.js
      - vite.config.js
jobs:
  build-and-push-to-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm@7.29.1
      - run: pnpm install
      - run: pnpm run build
        env:
          BASE_PATH: /sklein.xyz
      - run: touch build/.nojekyll
      - run: echo "sklein.xyz" > build/CNAME
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
